# Generated by Django 4.0.5 on 2022-07-01 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='Clave actividad')),
                ('nombre', models.TextField(max_length=30, verbose_name='Nombre de la actividad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('coment', ckeditor.fields.RichTextField(verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-created'],
            },
        ),
    ]
