# Generated by Django 4.0.5 on 2022-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_actividad_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado'),
        ),
    ]
