# Generated by Django 4.0.5 on 2022-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_actividad_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Registrado'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='idcurso',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
