# Generated by Django 4.0.5 on 2022-07-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentarios',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='comentarios',
            name='nombrecurso',
        ),
    ]
